export const LOGIN_ROUTE = '/login'
export const MAIN_ROUTE = '/mainpage'
export const ACCOUNT_ROUTE = '/account'
export const CREATEPRODUCT_ROUTE = '/createproduct'
export const ORDER_ROUTE = '/order'
export const NEWPRODUCT_ROUTE = '/newproduct'
export const MAKEORDER_ROUTE = '/makeorder'